#!/bin/bash
# Wazuh Docker Copyright (C) 2017, Wazuh Inc. 
# License GPLv2

# Paths
export WAZUH_DASHBOARD_BASE_DIR="/usr/share/wazuh-dashboard"
export WAZUH_DASHBOARD_CONF_DIR="${WAZUH_DASHBOARD_BASE_DIR}/config"
export WAZUH_DASHBOARD_DATA_DIR="${WAZUH_DASHBOARD_BASE_DIR}/data"
export WAZUH_DASHBOARD_CONF_FILE="${WAZUH_DASHBOARD_CONF_DIR}/opensearch_dashboards.yml"
export WAZUH_APP_CONF_FILE="${WAZUH_DASHBOARD_DATA_DIR}/wazuh/config/wazuh.yml"

# Environments for wazuh.yaml
export WAZUH_APP_PATTERN="${WAZUH_APP_PATTERN:-wazuh-alerts-*}"
export WAZUH_APP_CHECKS_PATTERN="${WAZUH_APP_CHECKS_PATTERN:-true}"
export WAZUH_APP_CHECKS_TEMPLATE="${WAZUH_APP_CHECKS_TEMPLATE:-true}"
export WAZUH_APP_CHECKS_API="${WAZUH_APP_CHECKS_API:-true}"
export WAZUH_APP_CHECKS_SETUP="${WAZUH_APP_CHECKS_SETUP:-true}"
export WAZUH_APP_EXTENSIONS_PCI="${WAZUH_APP_EXTENSIONS_PCI:-true}"
export WAZUH_APP_EXTENSIONS_GDPR="${WAZUH_APP_EXTENSIONS_GDPR:-true}"
export WAZUH_APP_EXTENSIONS_HIPAA="${WAZUH_APP_EXTENSIONS_HIPAA:-true}"
export WAZUH_APP_EXTENSIONS_NIST="${WAZUH_APP_EXTENSIONS_NIST:-true}"
export WAZUH_APP_EXTENSIONS_TSC="${WAZUH_APP_EXTENSIONS_TSC:-true}"
export WAZUH_APP_EXTENSIONS_AUDIT="${WAZUH_APP_EXTENSIONS_AUDIT:-true}"
export WAZUH_APP_EXTENSIONS_OSCAP="${WAZUH_APP_EXTENSIONS_OSCAP:-false}"
export WAZUH_APP_EXTENSIONS_CISCAT="${WAZUH_APP_EXTENSIONS_CISCAT:-false}"
export WAZUH_APP_EXTENSIONS_AWS="${WAZUH_APP_EXTENSIONS_AWS:-false}"
export WAZUH_APP_EXTENSIONS_GCP="${WAZUH_APP_EXTENSIONS_GCP:-false}"
export WAZUH_APP_EXTENSIONS_VIRUSTOTAL="${WAZUH_APP_EXTENSIONS_VIRUSTOTAL:-false}"
export WAZUH_APP_EXTENSIONS_OSQUERY="${WAZUH_APP_EXTENSIONS_OSQUERY:-false}"
export WAZUH_APP_EXTENSIONS_DOCKER="${WAZUH_APP_EXTENSIONS_DOCKER:-false}"
export WAZUH_APP_TIMEOUT="${WAZUH_APP_TIMEOUT:-20000}"
export WAZUH_APP_API_SELECTOR="${WAZUH_APP_API_SELECTOR:-true}"
export WAZUH_APP_IP_IGNORE="${WAZUH_APP_IP_IGNORE:-wazuh-alerts-*}"
export WAZUH_APP_WAZUH_MONITORING_ENABLED="${WAZUH_APP_WAZUH_MONITORING_ENABLED:-true}"
export WAZUH_APP_WAZUH_MONITORING_FREQUENCY="${WAZUH_APP_WAZUH_MONITORING_FREQUENCY:-900}"
export WAZUH_APP_WAZUH_MONITORING_SHARDS="${WAZUH_APP_WAZUH_MONITORING_SHARDS:-2}"
export WAZUH_APP_WAZUH_MONITORING_REPLICAS="${WAZUH_APP_WAZUH_MONITORING_REPLICAS:-0}"

# Environments for wazuh-dashboard.yaml
export WAZUH_DASHBOARD_HOST="${WAZUH_DASHBOARD_HOST:-0.0.0.0}"
export WAZUH_DASHBOARD_PORT_NUMBER="${WAZUH_DASHBOARD_PORT_NUMBER:-5601}"
export WAZUH_DASHBOARD_OPENSEARCH_HOSTS="${WAZUH_DASHBOARD_OPENSEARCH_HOSTS:-"wazuh.indexer"}"
export WAZUH_DASHBOARD_OPENSEARCH_PORT_NUMBER="${WAZUH_DASHBOARD_OPENSEARCH_PORT_NUMBER:-9200}"