#!/bin/bash
# Wazuh Docker Copyright (C) 2017, Wazuh Inc. 
# License GPLv2

# Paths
export WAZUH_VOLUME_DIR="/wazuh"
export WAZUH_DASHBOARD_VOLUME_DIR="${WAZUH_VOLUME_DIR}/wazuh-dasbhoard"

export WAZUH_DASHBOARD_BASE_DIR="/usr/share/wazuh-dashboard"
export WAZUH_DASHBOARD_CONF_DIR="${WAZUH_DASHBOARD_BASE_DIR}/config"
export WAZUH_DASHBOARD_DATA_DIR="${WAZUH_DASHBOARD_BASE_DIR}/data"
export WAZUH_DASHBOARD_BIN_DIR="${WAZUH_DASHBOARD_BASE_DIR}/bin"
export WAZUH_DASHBOARD_CONF_FILE="${WAZUH_DASHBOARD_CONF_DIR}/opensearch_dashboards.yml"
export WAZUH_DASHBOARD_KEYSTORE_FILE="${WAZUH_DASHBOARD_CONF_DIR}/opensearch_dashboards.keystore"
export WAZUH_DASHBOARD_APP_CONF_FILE="${WAZUH_DASHBOARD_DATA_DIR}/wazuh/config/wazuh.yml"

# Default custom scripts
export WAZUH_INIT_SCRIPTS_DIR=/init-scripts.d
export WAZUH_CUSTOM_SCRIPTS_DIR=/custom-scripts.d

# Default credentials for wazuh-dashboard
export WAZUH_DASHBOARD_USERNAME="${WAZUH_DASHBOARD_USERNAME:-admin}"
export WAZUH_DASHBOARD_PASSWORD="${WAZUH_DASHBOARD_PASSWORD:-secret}"

# Default Environments for wazuh-dashboard.yaml
export WAZUH_DASHBOARD_SERVER_HOST="${WAZUH_DASHBOARD_SERVER_HOST:-0.0.0.0}"
export WAZUH_DASHBOARD_SERVER_PORT="${WAZUH_DASHBOARD_SERVER_PORT:-5601}"
export WAZUH_DASHBOARD_OPENSEARCH_HOSTS="${WAZUH_DASHBOARD_OPENSEARCH_HOSTS:-"https://wazuh.indexer:9200"}"
export WAZUH_DASHBOARD_OPENSEARCH_SSL_VERIFICATION_MODE="${WAZUH_DASHBOARD_OPENSEARCH_SSL_VERIFICATION_MODE:-"certificate"}"
export WAZUH_DASHBOARD_OPENSEARCH_REQUESTHEADERSWHITELIST="${WAZUH_DASHBOARD_OPENSEARCH_REQUESTHEADERSWHITELIST:-"securitytenant,Authorization"}"
export WAZUH_DASHBOARD_OPENSEARCH_SECURITY_MUTITENANCY_ENABLED="${WAZUH_DASHBOARD_OPENSEARCH_SECURITY_MUTITENANCY_ENABLED:-false}"
export WAZUH_DASHBOARD_OPENSEARCH_SECURITY_READONLY_MODE_ROLES="${WAZUH_DASHBOARD_OPENSEARCH_SECURITY_READONLY_MODE_ROLES:-"kibana_read_only"}"
export WAZUH_DASHBOARD_SERVER_SSL_ENABLED="${WAZUH_DASHBOARD_SERVER_SSL_ENABLED:-true}"
export WAZUH_DASHBOARD_SERVER_SSL_KEY="${WAZUH_DASHBOARD_SERVER_SSL_KEY:-"/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem"}"
export WAZUH_DASHBOARD_SERVER_SSL_CERTIFICATE="${WAZUH_DASHBOARD_SERVER_SSL_CERTIFICATE:-"/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem"}"
export WAZUH_DASHBOARD_SERVER_SSL_CERTIFICATEAUTHORITIES="${WAZUH_DASHBOARD_SERVER_SSL_CERTIFICATEAUTHORITIES:-"/usr/share/wazuh-dashboard/certs/root-ca.pem"}"
export WAZUH_DASHBOARD_UISETTINGS_OVERRIDES_DEFAULTROUTE="${WAZUH_DASHBOARD_UISETTINGS_OVERRIDES_DEFAULTROUTE:-"/app/wazuh"}"

